---
title: "Bluff Lake Fishery Monitoring"
author: Michael E. Colvin
date: 31 October 2017
output:
  html_document:
    theme: flatly
    highlight: espresso
    toc: FALSE
bibliography: ref.bib
---

<!--
rmarkdown::render("index.Rmd")
-->

# Introduction

1. Bluff lake is an important lentic resource located in the Noxubee National Wildlife Refuge (NNWR). The lake is primarily used to achieve NNWR objectives for waterbirds. Additionally, the lake is the primary local resource providing angling opportunities to local residents and the nearby students of Mississippi State University. Anecdotally Bluff Lake was a productive fishery that satisfied local anglers. It is suggested that length limits on sportfish harvest improved the fishery (D. Jackson, MSU Pers. Com.). Changes of minimum length limits over time may have influenced the fishery but data is limited to assess this. Additionally, changes in lake level management may influence fishery productivity. 


2. Water level management is used to achieve NNWR management objectives.
Specifically, Bluff Lake water levels are manipulated to provide roosting and
foraging habitats for wood storks (Cite noxubee ccp)

 
1. Lake level manipulation and changes over time
1. Effects of lake level manipulation
1. Concentrate forage and predator fish
1. Results in poor fishing post drawdown but good growth
1. Limits recruitment of forage fish
1. Effect depends on when drawdown occurs
1. Effect depends on fish community and growth

Recreational fishing opportunities on the refuge are negatively 
impacted seasonally with the management of lakes for waterfowl and wood 
storks. Water levels are reduced during summer to allow for the growth 
of moist-soil plants used as food by ducks and to create shallow 
isolated water pools that trap fish as a food source for the summering 
wood storks. 


Manipulating water levels to control nuisance and exotic species, 
maintaining a balanced fisheries resource, providing food and nesting 
resources for both waterfowl and wading birds, and maintaining the 
diversity of the lakes are all issues that pose concerns. Most of these 
concerns are associated with the management of the water levels within 
the lakes. The manipulations of water levels allow management to better 
provide waterbird food resources and production of those resources while 
striving for minimal oxygen depletion which causes fish mortality. Also, 
from a public use standpoint, boat access becomes increasingly difficult 
with decreasing water depth within the lakes. 


manipulation of water levels at the expense of fisheries and forestry 
resources (Cite noxubee ccp p33) 


 P 96....
Objective A.7.2: When not in conflict with waterfowl and threatened and endangered species management, maintain a balanced native fisheries population in lakes by managing size distribution, ratio of predator to prey, mortality rates, and other key parameters.
* Strategy A.7.2.1: Monitor water levels using permanently fixed water level gauges.
* Strategy A.7.2.2: Use geographic information systems to record and assess water level measures.
* Strategy A.7.2.3: Periodically conduct fisheries monitoring.
* Strategy A.7.2.4: Create deep-water habitats within Bluff Lake and use soil from excavations to create forested islands to serve as possible future rookeries for birds.
* Strategy A.7.2.5: Use public use regulations as a tool in managing fish populations (i.e., slot or creel limits).

Objective A.7.3: Support existing populations of paddlefish by manipulating water flow from the lakes during the key spring spawning migration periods of February 15 to
May 1.
* Strategy A.7.3.1: Weekly release at least an estimated 400 cubic feet per second of water for at least one, 8-hour period using the Bluff Lake radial arm water control structure to increase water flow in areas down stream of structure.
* Strategy A.7.3.2: Maintain protection from the taking of paddlefish by anglers.

Objective A.7.5: Restore fish connectivity between the Bluff Lake and Noxubee River by installing fish passage structures for paddlefish and potential Gulf Coast walleye populations.
* Strategy A.7.5.1: Work with partners to better understand fish passage needs.
* Strategy A.7.5.2: If the existing structure is replaced, consider designing fish passage features.

March 1 to October 31- 6 weeks

    1. Changes in Bluff Lake elevation can influence
    downstream fish population and refuge objectives representing a 
    trade off of maintaining enough water in the lake while providing
    opportunities for Paddlefish passage. 
    1. Study objectives
        1. Quantify baseline fish assemblage and fishery values
        1. Identify Bluff Lake fishery and waterbird management objectives
        1. Develop a prototype decision support tool for water level management
        given varying fishery and waterbird objectives.
1. Methods
    1. Study area
    1. Fish assemblage 
        1. Species composition
        1. Growth & size structure
    1. Angler preferences and harvest
        1. Effort and harvest
            1. Creel survey (Miranda et al. xxxx)
                1. Stratified- weekend and holiday, weekday
                1. 
            1. Instantaneous angler counts (Bank and Boats)
            1. Angler objectives
    1. Identifying management objectives
        1. NNWR & USFWS
            1. Wood stork
            1. ????
            1. American alligator
        1. Angler
        1. Non consumptive users (e.g., birders, paddlers)
1. Anticipated results and deliverables




1. Timeline

Year 1.
