---
title: "Combined Analysis"
author: "V. Starnes"
date: "April 23, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Linking WSE to Volume, echo=FALSE}
dat <- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/Bathymetry/WCS_BTTMUP_2_2.csv")
library(scales)
library(mgcv)
library(lubridate)
library(dplyr)
library(tidyverse)

# ---- Lake Volume
# one point=6.25m^2
Z <- c(dat$POINT_Z < (66.45402+0))
Z <- c((66.45402+0-Z))
Z <- Z*1.56
Z <- sum(Z)
B <- c(dat$POINT_Z < (66.45402+.22))
B <- c((66.45402+.22-B))
B <- B*1.56
B <- sum(B) #convert to volume
BB <- c(dat$POINT_Z < (66.45402+.44)) #add board hight and required depth
BB <- c((66.45402+.44-BB))
BB <- BB*1.56
BB <- sum(BB)
BBB <- c(dat$POINT_Z < (66.45402+.66)) #add board hight and required depth
BBB <- c((66.45402+.66-BBB))
BBB <- BBB*1.56
BBB <- sum(BBB)
BBBB <- c(dat$POINT_Z < (66.45402+.88)) #add board hight and required depth
BBBB <- c((66.45402+.88-BBBB))
BBBB <- BBBB*1.56
BBBB <- sum(BBBB)
BBBBB <- c(dat$POINT_Z < (66.45402+1.1)) #add board hight and required depth
BBBBB <- c((66.45402+1.1-BBBBB))
BBBBB <- BBBBB*1.56
BBBBB <- sum(BBBBB)
BBBBBB <- c(dat$POINT_Z < (66.45402+1.32)) #add board hight and required depth
BBBBBB <- c((66.45402+1.32-BBBBBB))
BBBBBB <- BBBBBB*1.56
BBBBBB <- sum(BBBBBB)
BBBBBBB <- c(dat$POINT_Z < (66.45402+1.54)) #add board hight and required depth
BBBBBBB <- c((66.45402+1.54-BBBBBBB))
BBBBBBB <- BBBBBBB*1.56
BBBBBBB <- sum(BBBBBBB)
BBBBBBBB <- c(dat$POINT_Z < (66.45402+1.76)) #add board hight and required depth
BBBBBBBB <- c((66.45402+1.76-BBBBBBBB))
BBBBBBBB <- BBBBBBBB*1.56
BBBBBBBB <- sum(BBBBBBBB)
BBBBBBBBB <- c(dat$POINT_Z < (66.45402+1.98)) #add board hight and required depth
BBBBBBBBB <- c((66.45402+1.98-BBBBBBBBB))
BBBBBBBBB <- BBBBBBBBB*1.56
BBBBBBBBB <- sum(BBBBBBBBB)
elevation <- c(66.45402, 66.67402, 66.89402, 67.11402, 67.33402,
               67.55402, 67.77402, 67.99402, 68.21402, 68.43402)
volume <- c(Z, B, BB, BBB, BBBB, BBBBB, BBBBBB, BBBBBBB, BBBBBBBB, BBBBBBBBB)
plot(elevation, volume, xlab="Water Surface Elevation", ylab="Volume (m^3)", main = "Bluff Lake Volume", type="l", col="red", ylim=c(100500000,102000000), xlim=c(66.5,68.5))
gam_1 <- gam(volume ~ s(elevation, bs = "cr"),
             family = gaussian)
summary(gam_1)
gam_2 <- gam(elevation ~ s(volume, bs = "cr"),
             family = gaussian)
summary(gam_2)
par(new=T)
plot(gam_1$fitted.values~elevation, ylim=c(100500000,102000000), xlim=c(66.5,68.5), col="blue", type="l")
```

## Lake Level Dynamics

```{r lake, echo=FALSE}
par(mfrow=c(1,1))
dat2<- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/DischargeDataMacon15min.csv")
dat2$Date.Time <- as.POSIXct(dat2$Date.Time, format="%m/%d/%Y %H:%M")
dat2$month<- lubridate::month(as.POSIXct(dat2$Date.Time, format="%Y/%m/%d %H:%M"), label= T)
dat2Jan<-subset(dat2, dat2$month=="Jan")
plot(dat2Jan$ï..CFS~dat2Jan$Date.Time, type='l',col="red")
#ggplot(data = dat2Jan, aes(x = ï..datetime, y = CFS))+
 # geom_line(color = "#00BF7D", size = 2)

Elevation <- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/Level_loggersEL.csv")
Elevation <- subset(Elevation, Elevation$ï..Location == "Cypress")
Elevation$Date.Time <- (as.POSIXct(Elevation$Date.Time, format="%m/%d/%Y %H:%M"))
Elevation$month<- lubridate::month(as.POSIXct(Elevation$Date.Time, format="%Y/%m/%d %H:%M"), label= T)
ElevationJan<-subset(Elevation, Elevation$month=="Jan")
par(new=TRUE)
ElevationJan<-ElevationJan[order(ElevationJan$Date.Time),]
plot(WSElevation~Date.Time,ElevationJan, main="January",type="l", 
     xaxt = "n", yaxt = "n", ylab = "", xlab = "")
legend("topright", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
#ggplot(data = ElevationJan, aes(x = Date.Time, y = WSElevation))+
 # geom_line(color = "#6BB100", size = 2)
#DECEMBER
dat2Dec<-subset(dat2, dat2$month=="Dec")
plot(dat2Dec$ï..CFS~dat2Dec$Date.Time, main="December",type='l',col="red")
ElevationDec<-subset(Elevation, Elevation$month=="Dec")
par(new=TRUE)
ElevationDec<-ElevationDec[order(ElevationDec$Date.Time),]
plot(WSElevation~Date.Time,ElevationDec, type="l", 
     xaxt = "n", yaxt = "n", ylab = "", xlab = "")
legend("topleft", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))

#November
dat2Nov<-subset(dat2, dat2$month=="Nov")
plot(dat2Nov$ï..CFS~dat2Nov$Date.Time, main="November",type='l',col="red")
ElevationNov<-subset(Elevation, Elevation$month=="Nov")
par(new=TRUE)
ElevationNov<-ElevationNov[order(ElevationNov$Date.Time),]
plot(WSElevation~Date.Time,ElevationNov, type="l", 
     xaxt = "n", yaxt = "n", ylab = "", xlab = "")
legend("topright", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
#October
dat2Oct<-subset(dat2, dat2$month=="Oct")
  plot(dat2Oct$ï..CFS~dat2Oct$Date.Time , main="October",type='l',col="red")
ElevationOct<-subset(Elevation, Elevation$month=="Oct")
par(new=TRUE)
ElevationOct<-ElevationOct[order(ElevationOct$Date.Time),]
plot(WSElevation~Date.Time,ElevationOct, type="l", 
     xaxt = "n", yaxt = "n", ylab = "", xlab = "")
legend("topleft", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
#September
dat2Sep<-subset(dat2, dat2$month=="Sep")
plot(dat2Sep$ï..CFS~dat2Sep$Date.Time, main="September",type='l',col="red", xaxt = "n", yaxt = "n", ylab = "", xlab = "")
ElevationSep<-subset(Elevation, Elevation$month=="Sep")
par(new=TRUE)
ElevationSep<-ElevationSep[order(ElevationSep$Date.Time),]
plot(WSElevation~Date.Time,ElevationSep, type="l")
legend("topright", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
#August
dat2Aug<-subset(dat2, dat2$month=="Aug")
plot(dat2Aug$ï..CFS~dat2Aug$Date.Time, main="August",type='l',col="red", xaxt = "n", yaxt = "n", ylab = "", xlab = "")
ElevationAug<-subset(Elevation, Elevation$month=="Aug")
par(new=TRUE)
ElevationAug<-ElevationAug[order(ElevationAug$Date.Time),]
plot(WSElevation~Date.Time,ElevationAug, type="l")
legend("topleft", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
#July
dat2Jul<-subset(dat2, dat2$month=="Jul")
  plot(dat2Jul$ï..CFS~dat2Jul$Date.Time, main="July",type='l',col="red")
ElevationJul<-subset(Elevation, Elevation$month=="Jul")
par(new=TRUE)
ElevationJul<-ElevationJul[order(ElevationJul$Date.Time),]
plot(WSElevation~Date.Time,ElevationJul, type="l", 
     xaxt = "n", yaxt = "n", ylab = "", xlab = "")
legend("topleft", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
#June
dat2Jun<-subset(dat2, dat2$month=="Jun")
plot(dat2Jun$ï..CFS~dat2Jun$Date.Time, main="June",type='l',col="red")
ElevationJun<-subset(Elevation, Elevation$month=="Jun")
par(new=TRUE)
ElevationJun<-ElevationJun[order(ElevationJun$Date.Time),]
plot(WSElevation~Date.Time,ElevationJun, type="l", 
     xaxt = "n", yaxt = "n", ylab = "", xlab = "")
legend("topright", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
#May
dat2May<-subset(dat2, dat2$month=="May")
plot(dat2May$ï..CFS~dat2May$Date.Time, main="May",type='l',col="red")
ElevationMay<-subset(Elevation, Elevation$month=="May")
par(new=TRUE)
ElevationMay<-ElevationMay[order(ElevationMay$Date.Time),]
plot(WSElevation~Date.Time,ElevationMay, type="l", 
     xaxt = "n", yaxt = "n", ylab = "", xlab = "")
legend("topright", c("Discharge", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))

```

## Predict WSE given Discharge

```{r Pred-WSE, echo=FALSE}
#Links between water surface elevation and Macon gauge discharge
par(mfrow=c(1,1))
library(tidyverse)
library(lubridate)
library(plyr)
library(data.table)
library(mgcv)
library(car)
library(ggplot2)
library(grid)
dat2<- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/DischargeDataMacon15min.csv")
dat2$Date.Time <- as.POSIXct(dat2$Date.Time, format="%m/%d/%Y %H:%M")
dat2$month<- lubridate::month(as.POSIXct(dat2$Date.Time, format="%Y/%m/%d %H:%M"), label = F)
dat2$Date.Time<-round_date(dat2$Date.Time, "30 mins")
CMS<-ddply(dat2, c("Date.Time","month"), summarize,
           meanCMS=mean(ï..CFS))

Elevation <- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/Level_loggersEL.csv")
Elevation <- subset(Elevation, Elevation$ï..Location == "Cypress")
Elevation$Date.Time <- (as.POSIXct(Elevation$Date.Time, format="%m/%d/%Y %H:%M"))
Elevation$month<- lubridate::month(as.POSIXct(Elevation$Date.Time, format="%Y/%m/%d %H:%M"), label= F)
data<-merge(Elevation, CMS)
#try GAM
library(mgcv)
library(data.table)

matrix_gam <- data.table(Ele = data$WSElevation,
                         CMS = data$meanCMS,
                         Month = data$month)

gam_4 <- gam(Ele ~ te(CMS, Month,
                       k = c(48, 8),
                       bs = c("cr", "ps")),
             data = matrix_gam,
             family = gaussian)
summary(gam_4)
summary(gam_4)$s.table

data$FitG4<- gam_4$fitted.values
plot(FitG4~Date.Time, data, type="l", col="red", ylim=c(68.6,69.8), 
     main="GAM Model 4", xlab="Date", ylab="Water Surface Elevation")
par(new=T)
plot(WSElevation~Date.Time, data, type="l", col="blue", ylim=c(68.6,69.8),ylab=NA, xlab=NA)
legend("topleft", c("Predicted", "Lake Elevation"),
       col = c("red", "black"), lty = c(1, 1))
```

##Predict Change in Volume given Discharge 

```{r Pred-Volume, echo=FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(zoo)
library(dplyr)
library(mgcv)
 dat<- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/DailyMacon01011945_01012020.csv")
 dat$ï..datetime <- as.POSIXct(dat$ï..datetime, format="%m/%d/%Y")
 names(dat)[1]<-"Date"
 #add in missing dates
 Date<-seq(as.Date("1945/1/1"), as.Date("2019/12/31"), "days")
 Date<-as.data.frame(Date)
 Date$Date<-as.POSIXct(Date$Date, format="%Y/%m/%d")
 Date$Date<-round_date(Date$Date, "day")
 library(dplyr)
 dat<-left_join(Date, dat, by = "Date")
 dat$Discharge_cfs<-na.approx(dat$Discharge_cfs)
 dat$Discharge_cms<-dat$Discharge_cfs*0.028316847

 dat$month<- lubridate::month(as.POSIXct(dat$Date, format="%Y/%m/%d"), label = T)
 dat$year<-lubridate::year(dat$Date)
 dat$day<-lubridate::day(dat$Date)
 dat$DeltaCMS<-c(NA,diff(dat$Discharge_cms))
 dat$meanCMS<-dat$Discharge_cms

#
#####
 dat2<- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/DischargeDataMacon15min.csv")
 dat2$Date.Time <- as.POSIXct(dat2$Date.Time, format="%m/%d/%Y %H:%M")
 dat2$month<- lubridate::month(as.POSIXct(dat2$Date.Time, format="%Y/%m/%d %H:%M"), label = T)
 dat2$Date.Time<-round_date(dat2$Date.Time, "30 mins")
 CMS<-ddply(dat2, c("Date.Time","month"), summarize,
            meanCMS=mean(ï..CFS))
 Elevation <- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/Level_loggersEL.csv")
 Elevation <- subset(Elevation, Elevation$ï..Location == "Cypress")
 Elevation$Date.Time <- (as.POSIXct(Elevation$Date.Time, format="%m/%d/%Y %H:%M"))
 Elevation$month<- lubridate::month(as.POSIXct(Elevation$Date.Time, format="%Y/%m/%d %H:%M"), label= T)
 data<-merge(Elevation, CMS)

 M3<-lm(WSElevation~meanCMS+month+ meanCMS*month,data)
 summary(M3)

# #try GAM
 library(mgcv)
 library(data.table)
 #group data by day
 data$Date.Time<-round_date(data$Date.Time, "day")
 data<-data %>% dplyr::group_by(data$Date.Time) %>%
   dplyr::summarise_all(funs(mean))
 data2<-data

 #differce between days elevation
 data2$DeltaEle<-c(NA, diff(data2$WSElevation))
 #convert Elevation to volume
 data2$elevation<-data2$WSElevation
 data2$Vol<- predict(gam_1, data2)
  #change in volume
 data2$DeltaVol<-c(NA,diff(data2$Vol))
 #difference between days CMS
 data2$DeltaCMS<-c(NA,diff(data2$meanCMS))
 #add month back
 data2$month<- lubridate::month(as.POSIXct(data2$Date.Time, format="%m/%d/%Y"), label= T)
# #Get rid of Negatives
 data4<-data2
 data4 <- filter(data4, DeltaVol>0)
 data4 <- filter(data4, DeltaCMS>0)
 Posgam <- gam(DeltaVol ~ s(meanCMS),
               data = data4,
               family = gaussian)
 summary(Posgam)
 data5<-data2
 data5 <- filter(data5, DeltaVol<0)
 data5 <- filter(data5, DeltaCMS<0)
 Neggam <- gam(DeltaVol ~ s(meanCMS),
               data = data5,
               family = gaussian)
summary(Neggam)
 data5<-data2
 data5 <- filter(data5, DeltaVol<0)
 data5 <- filter(data5, DeltaCMS<0)
 Neggam <- gam(DeltaVol ~ s(meanCMS),
               data = data5,
               family = gaussian)
summary(Neggam)
#Plots
plot(DeltaVol~meanCMS, data4, col="blue", main="Change in Lake Volume vs Discharge")
par(new=T)
plot(Posgam$fitted.values~data4$meanCMS, col="red", ylab=NA, xlab=NA, ylim=c(min(data4$DeltaVol), max(data4$DeltaVol)))
legend("topleft", c("Predicted", "Actual"),
       col = c("red", "blue"), lty = c(1, 1))
plot(DeltaVol~meanCMS, data5, col="blue", main="Change in Lake Volume vs Discharge")
par(new=T)
plot(Neggam$fitted.values~data5$meanCMS, col="red", ylab=NA, xlab=NA, ylim=c(min(data5$DeltaVol), max(data5$DeltaVol)))
legend("bottomleft", c("Predicted", "Actual"),
       col = c("red", "blue"), pch = c(1, 1))
####Now use GAM to predict change in volume given discharge
datP <- filter(dat, DeltaCMS>0)
datP$DeltaVol<-predict(Posgam, datP)
datN <- filter(dat, DeltaCMS<0)
datN$DeltaVol<-predict(Neggam, datN)
data<-rbind(datN, datP)
names(data)[1]<-"Date"

write.csv(data, "~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/PADDLE_DISCHARGE22.csv")

```

```{r Paddlefish, echo=FALSE}
fish=read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/PADDLE_DISCHARGE22.csv")

fish$Date<-as.POSIXct(strptime(as.character(fish$Date),"%Y-%m-%d"))
fish$month<-as.numeric(format(fish$Date, "%m"))
fish$year<-as.numeric(format(fish$Date, "%Y"))
str(fish)
fish<-fish %>% mutate(Date=ymd(Date)) #make this the proper format
str(fish)

a=fish %>% dplyr::group_by(year, month) %>% dplyr::summarise(Date=max(Date)) #get the max date for each month-year

fish2=data.frame()#create an empty data frame

for(i in 1:nrow(a)){
  b=data.frame(Date=seq(ymd(paste(a$year[i], a$month[i], "01", sep="-")), a$Date[i], 1))
  fish2=rbind(fish2, b)
} #makes sure there is each day in each month in each year


fish3=left_join(fish2, fish) 
#interpolate missing values
fish3$DeltaVol<-na.spline(fish3$DeltaVol)
fish3$Date2<-as.POSIXct(strptime(as.character(fish3$Date),"%Y-%m-%d"))
fish3$month<-as.numeric(format(fish3$Date2, "%m"))
fish3$year<-as.numeric(format(fish3$Date2, "%Y"))
fish3$day<-as.numeric(format(fish3$Date2, "%d"))

fish3=mutate(fish3, fishD=ifelse(day==1|day==7|day==14|day==21|day==28, 325440, 0)) #for the 1st and 15th create the discharges
#Run different discharges: 0, 81360, 162720, 244080, 325440, 488160


## COMBINE YEAR AND MONTH TO LOOP OVER 
fish3$yr_month<-paste(fish3$year,fish3$month,sep="-")
fish3<-fish3[order(fish3$Date2),]
## YEAR MONTH COMBINATIONS TO LOOP OVER
combos<-unique(fish3$yr_month)
combos<- combos[-length(combos)]## DROP 2020-01 ONLY 1 DAY THERE

fish3$volume<-NA  ## KEEP TRACK OF VOLUME THAT CHANGES DAILY AS VOL[PREV DAY] + IN - OUT
for(i in 1:length(combos))
    {
    indx<-which(fish3$yr_month==combos[i]) # ROW INDICES FOR THE YEAR MONTH COMBINATION SHOULD BE A VECTOR OF ~ 30 VALUES
    ## FIRST DAY
    first_day_row_indx<- indx[1]
    fish3$volume[first_day_row_indx]<-101976480
    ## INITIAL VOLUME AT THE FIRST OF THE MONTH-
    #100447697 100762656 101047557 101227827 101257957 
    #101294378 101377521 101514389 101703873 101976480
    ## LOOP OVER REMAINING DAYS IN THE MONTH
    for(j in 2:length(indx))
        {
        current_day<- indx[j]
        day_before<- indx[j-1]
        fish3$volume[current_day]<- fish3$volume[day_before]+fish3$DeltaVol[current_day]-fish3$fishD[current_day]
        }
    }

write.csv(fish3, "~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_11.3cms_discharge/9Boards.csv")

theme_set(theme_classic())

Jan<-subset(fish3, month==1)
ggplot(Jan, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="January Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
       ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")
  


Feb<-subset(fish3, month==2)
ggplot(Feb, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="February Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Mar<-subset(fish3, month==3)
ggplot(Mar, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="March Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Apr<-subset(fish3, month==4)
ggplot(Apr, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="April Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

May<-subset(fish3, month==5)
ggplot(May, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="May Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Jun<-subset(fish3, month==6)
ggplot(Jun, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="June Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Jul<-subset(fish3, month==7)
ggplot(Jul, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="July Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Aug<-subset(fish3, month==8)
ggplot(Mar, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="August Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Sep<-subset(fish3, month==9)
ggplot(Sep, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="September Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Oct<-subset(fish3, month==10)
ggplot(Oct, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="October Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Nov<-subset(fish3, month==11)
ggplot(Nov, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="November Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")

Dec<-subset(fish3, month==12)
ggplot(Dec, aes(day, volume, group = year, color = year)) + 
  geom_line( )+
  labs(title="December Time Series of Lake Volume", 
       y="Volume m^3",
       x="Day of Month"
  ) +
  ylim(99000000, 103500000)+
  geom_hline(yintercept=101976479)+
  geom_hline(yintercept=101703873)+
  geom_hline(yintercept=101514389)+
  geom_hline(yintercept=101377521)+
  geom_hline(yintercept=101294378)+
  geom_hline(yintercept=101257987)+
  geom_hline(yintercept=101227827)+
  geom_hline(yintercept=101047557)+
  geom_hline(yintercept=100762655)+
  geom_hline(yintercept=100447696, col="red")



```

```{r Objectives.VS.Elevation, echo=FALSE}
dat <- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/Bathymetry/WCS_BTTMUP_2_2.csv")
# ---- Waterbirds
# areas must be less than 20 cm in depth
Z <- length(which(dat$POINT_Z > (66.45402-.20))) #add board hight and required depth
Z <- Z*1.56 #convert to area
B <- length(which(dat$POINT_Z > (66.45402+.22-.20))) #add board hight and required depth
B <- B*1.56 #convert to area
BB <- length(which(dat$POINT_Z > (66.45402+.44-.20))) #add board hight and required depth
BB <- BB*1.56 #convert to area
BBB <- length(which(dat$POINT_Z > (66.45402+.66-.20))) #add board hight and required depth
BBB <- BBB*1.56 #convert to area
BBBB <- length(which(dat$POINT_Z > (66.45402+.88-.20))) #add board hight and required depth
BBBB <- BBBB*1.56 #convert to area
BBBBB <- length(which(dat$POINT_Z > (66.45402+1.1-.20))) #add board hight and required depth
BBBBB <- BBBBB*1.56 #convert to area
BBBBBB <- length(which(dat$POINT_Z > (66.45402+1.32-.20))) #add board hight and required depth
BBBBBB <- BBBBBB*1.56 #convert to area
BBBBBBB <- length(which(dat$POINT_Z > (66.45402+1.54-.20))) #add board hight and required depth
BBBBBBB <- BBBBBBB*1.56 #convert to area
BBBBBBBB <- length(which(dat$POINT_Z > (66.45402+1.76-.20))) #add board hight and required depth
BBBBBBBB <- BBBBBBBB*1.56 #convert to area
BBBBBBBBB <- length(which(dat$POINT_Z > (66.45402+1.98-.20))) #add board hight and required depth
BBBBBBBBB <- BBBBBBBBB*1.56 #convert to area
elevation <- c(66.45402, 66.67402, 66.89402, 67.11402, 67.33402,
               67.55402, 67.77402, 67.99402, 68.21402, 68.43402)
WB <- c(Z, B, BB, BBB, BBBB, BBBBB, BBBBBB, BBBBBBB, BBBBBBBB, BBBBBBBBB)/10000
plot(elevation, WB, xlab="Water Surface Elevation", ylab="Hectares (<20cm)", main = "Waterbird Habitat", type="l", col="red")

# ---- Waterfowl
# DED/m^2=0.4374
# Dry Areas
Z <- sum(dat$POINT_Z > (66.45402)) #add board hight and required depth
Z <- Z*1.56*0.4374 #convert to DED per area
B <- sum(dat$POINT_Z > (66.45402+.22)) #add board hight and required depth
B <- B*1.56*0.4374
BB <- sum(dat$POINT_Z > (66.45402+.44)) #add board hight and required depth
BB <- BB*1.56*0.4374
BBB <- sum(dat$POINT_Z > (66.45402+.66)) #add board hight and required depth
BBB <- BBB*1.56*0.4374
BBBB <- sum(dat$POINT_Z > (66.45402+.88)) #add board hight and required depth
BBBB <- BBBB*1.56*0.4374
BBBBB <- sum(dat$POINT_Z > (66.45402+1.1)) #add board hight and required depth
BBBBB <- BBBBB*1.56*0.4374
BBBBBB <- sum(dat$POINT_Z > (66.45402+1.32)) #add board hight and required depth
BBBBBB <- BBBBBB*1.56*0.4374
BBBBBBB <- sum(dat$POINT_Z > (66.45402+1.54)) #add board hight and required depth
BBBBBBB <- BBBBBBB*1.56*0.4374
BBBBBBBB <- sum(dat$POINT_Z > (66.45402+1.76)) #add board hight and required depth
BBBBBBBB <- BBBBBBBB*1.56*0.4374
BBBBBBBBB <- sum(dat$POINT_Z > (66.45402+1.98)) #add board hight and required depth
BBBBBBBBB <- BBBBBBBBB*1.56*0.4374
elevation <- c(66.45402, 66.67402, 66.89402, 67.11402, 67.33402,
               67.55402, 67.77402, 67.99402, 68.21402, 68.43402)
WF <- c(Z, B, BB, BBB, BBBB, BBBBB, BBBBBB, BBBBBBB, BBBBBBBB, BBBBBBBBB)/1000000
plot(elevation, WF, xlab="Water Surface Elevation", ylab="DEDs (millions)", main = "Duck Energy Days", type="l", col="red")

# ---- Fish
# Areas greater than 1 meter in depth
Z <- sum(dat$POINT_Z < (66.45402-1)) #add board hight and required depth
Z <- Z*1.56 #convert to area
B <- sum(dat$POINT_Z < (66.45402-1+.22)) #add board hight and required depth
B <- B*1.56 #convert to area
BB <- sum(dat$POINT_Z < (66.45402-1+.44)) #add board hight and required depth
BB <- BB*1.56 #convert to area
BBB <- sum(dat$POINT_Z < (66.45402-1+.66)) #add board hight and required depth
BBB <- BBB*1.56 #convert to area
BBBB <- sum(dat$POINT_Z < (66.45402-1+.88)) #add board hight and required depth
BBBB <- BBBB*1.56 #convert to area
BBBBB <- sum(dat$POINT_Z < (66.45402-1+1.1)) #add board hight and required depth
BBBBB <- BBBBB*1.56 #convert to area
BBBBBB <- sum(dat$POINT_Z < (66.45402-1+1.32)) #add board hight and required depth
BBBBBB <- BBBBBB*1.56 #convert to area
BBBBBBB <- sum(dat$POINT_Z < (66.45402-1+1.54)) #add board hight and required depth
BBBBBBB <- BBBBBBB*1.56 #convert to area
BBBBBBBB <- sum(dat$POINT_Z < (66.45402-1+1.76)) #add board hight and required depth
BBBBBBBB <- BBBBBBBB*1.56 #convert to area
BBBBBBBBB <- sum(dat$POINT_Z < (66.45402-1+1.98)) #add board hight and required depth
BBBBBBBBB <- BBBBBBBBB*1.56 #convert to area
elevation <- c(66.45402, 66.67402, 66.89402, 67.11402, 67.33402,
               67.55402, 67.77402, 67.99402, 68.21402, 68.43402)
Fish <- c(Z, B, BB, BBB, BBBB, BBBBB, BBBBBB, BBBBBBB, BBBBBBBB, BBBBBBBBB)/10000
plot(elevation, Fish, xlab="Water Surface Elevation", ylab="Hectares (>1m)", main = "Fish Habitat", type="l", col="red")
#### ---- Anglers
# For now, following fish model, Areas greater than 1 meter in depth
Adat<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/Bathymetry/Anglers.csv")
Z <- sum(Adat$POINT_Z < (66.45402-1)) #add board hight and required depth
Z <- Z*1.56 #convert to area
B <- sum(Adat$POINT_Z < (66.45402-1+.22)) #add board hight and required depth
B <- B*1.56 #convert to area
BB <- sum(Adat$POINT_Z < (66.45402-1+.44)) #add board hight and required depth
BB <- BB*1.56 #convert to area
BBB <- sum(Adat$POINT_Z < (66.45402-1+.66)) #add board hight and required depth
BBB <- BBB*1.56 #convert to area
BBBB <- sum(Adat$POINT_Z < (66.45402-1+.88)) #add board hight and required depth
BBBB <- BBBB*1.56 #convert to area
BBBBB <- sum(Adat$POINT_Z < (66.45402-1+1.1)) #add board hight and required depth
BBBBB <- BBBBB*1.56 #convert to area
BBBBBB <- sum(Adat$POINT_Z < (66.45402-1+1.32)) #add board hight and required depth
BBBBBB <- BBBBBB*1.56 #convert to area
BBBBBBB <- sum(Adat$POINT_Z < (66.45402-1+1.54)) #add board hight and required depth
BBBBBBB <- BBBBBBB*1.56 #convert to area
BBBBBBBB <- sum(Adat$POINT_Z < (66.45402-1+1.76)) #add board hight and required depth
BBBBBBBB <- BBBBBBBB*1.56 #convert to area
BBBBBBBBB <- sum(Adat$POINT_Z < (66.45402-1+1.98)) #add board hight and required depth
BBBBBBBBB <- BBBBBBBBB*1.56 #convert to area
elevation <- c(66.45402, 66.67402, 66.89402, 67.11402, 67.33402,
               67.55402, 67.77402, 67.99402, 68.21402, 68.43402)
Anglers <- c(Z, B, BB, BBB, BBBB, BBBBB, BBBBBB, BBBBBBB, BBBBBBBB, BBBBBBBBB)/10000
plot(elevation, Anglers, xlab="Water Surface Elevation", ylab="Hectares (>1m)", main = "Shoreline Fishing", type="l", col="red")
# Need to deliniate shorelines and establish "end" of boat ramp
#areas >.5m in depth
Bdat<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/Depth-Mapping/_dat/Bathymetry/Boat.csv")
Z <- sum(Bdat$POINT_Z < (66.45402)) #add board hight and required depth
Z <- Z*1.56 #convert to area
B <- sum(Bdat$POINT_Z < (66.45402+.22-0.5)) #add board hight and required depth
B <- B*1.56 #convert to area
BB <- sum(Bdat$POINT_Z < (66.45402+.44-0.5)) #add board hight and required depth
BB <- BB*1.56 #convert to area
BBB <- sum(Bdat$POINT_Z < (66.45402+.66-0.5)) #add board hight and required depth
BBB <- BBB*1.56 #convert to area
BBBB <- sum(Bdat$POINT_Z < (66.45402+.88-0.5)) #add board hight and required depth
BBBB <- BBBB*1.56 #convert to area
BBBBB <- sum(Bdat$POINT_Z < (66.45402+1.1-0.5)) #add board hight and required depth
BBBBB <- BBBBB*1.56 #convert to area
BBBBBB <- sum(Bdat$POINT_Z < (66.45402+1.32-0.5)) #add board hight and required depth
BBBBBB <- BBBBBB*1.56 #convert to area
BBBBBBB <- sum(Bdat$POINT_Z < (66.45402+1.54-0.5)) #add board hight and required depth
BBBBBBB <- BBBBBBB*1.56 #convert to area
BBBBBBBB <- sum(Bdat$POINT_Z < (66.45402+1.76-0.5)) #add board hight and required depth
BBBBBBBB <- BBBBBBBB*1.56 #convert to area
BBBBBBBBB <- sum(Bdat$POINT_Z < (66.45402+1.98-0.5)) #add board hight and required depth
BBBBBBBBB <- BBBBBBBBB*1.56 #convert to area
elevation <- c(66.45402, 66.67402, 66.89402, 67.11402, 67.33402,
               67.55402, 67.77402, 67.99402, 68.21402, 68.43402)
Ramp <- c(Z, B, BB, BBB, BBBB, BBBBB, BBBBBB, BBBBBBB, BBBBBBBB, BBBBBBBBB)
plot(elevation, Ramp, xlab="Water Surface Elevation", ylab="Wetted Area (m^2)", main = "Ramp Access", type="l", col="red")


```

```{r Utilities, echo=FALSE}
WB<- rescale(WB, to=c(0,1))
plot(elevation, WB, xlab="Water Surface Elevation", ylab="Utility", main = "Waterbird Habitat", type="l", col="red")
WBM <- gam(WB ~ s(elevation, bs = "cr"),
             family = gaussian)
par(new=T)
plot(WBM$fitted.values~elevation, col="blue", type="l")
WF<-rescale(WF, to=c(0,1))
plot(elevation, WF, xlab="Water Surface Elevation", ylab="Utility", main = "Duck Energy Days", type="l", col="red")
WFM <- gam(WF ~ s(elevation, bs = "cr"),
             family = gaussian)
par(new=T)
plot(WFM$fitted.values~elevation, col="blue", type="l")
Fish <-rescale(Fish, to=c(0,1))
plot(elevation, Fish, xlab="Water Surface Elevation", ylab="Utility", main = "Fish Habitat", type="l", col="red")
FishM <- gam(Fish ~ s(elevation, bs = "cr"),
             family = gaussian)
par(new=T)
plot(FishM$fitted.values~elevation, col="blue", type="l")
Anglers<-rescale(Anglers, to=c(0,1))
plot(elevation, Anglers, xlab="Water Surface Elevation", ylab="Utility", main = "Shoreline Fishing", type="l", col="red")
AnglersM <- gam(Anglers ~ s(elevation, bs = "cr"),
             family = gaussian)
par(new=T)
plot(AnglersM$fitted.values~elevation, col="blue", type="l")
Ramp<-rescale(Ramp, to=c(0,1))
plot(elevation, Ramp, xlab="Water Surface Elevation", ylab="Utility", main = "Ramp Access", type="l", col="red")
RampM <- gam(Ramp ~ s(elevation, bs = "cr"),
                family = gaussian)
par(new=T)
plot(RampM$fitted.values~elevation, col="blue", type="l")
```

```{r Utilities, echo=FALSE}
#Utilities
dat2<- read.csv("~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_11.3cms_discharge/9Boards.csv")
dat2$elevation<-predict(gam_2, dat2)
dat2$WFUt<-predict(WFM, dat2)
dat2$WBUt<-predict(WBM, dat2)
dat2$FishUt<-predict(FishM, dat2)
dat2$AngUt<-predict(AnglersM, dat2)
dat2$RampUt<-predict(RampM, dat2)

dat2$WFUt <- ifelse(dat2$WFUt< 0, 0, dat2$WFUt)
dat2$WBUt<- ifelse(dat2$WBUt < 0, 0, dat2$WBUt)
dat2$FishUt <- ifelse(dat2$FishUt  < 0, 0, dat2$FishUt )
dat2$AngUt <- ifelse(dat2$AngUt < 0, 0, dat2$AngUt)
dat2$RampUt <- ifelse(dat2$RampUt < 0, 0, dat2$RampUt)

dat2$Utility<- (dat2$RampUt)+(dat2$AngUt)+(dat2$FishUt)+(dat2$WBUt)+(dat2$WFUt)+(1)

write.csv(dat2, "~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_11.3cms_discharge/9Boards.csv")


#weekly average
dat2<-dat2 %>%
  filter(!is.na(Utility))
dat2$Date <- as.POSIXct(dat2$Date)
dat2$Date <-lubridate::round_date(dat2$Date, "7 days")
dat2$Date <- as.POSIXct(dat2$Date, format="%m-%d-%Y")
dat2 <- dat2 %>%
  dplyr::group_by(Date) %>%
  dplyr::summarize(mUtility = mean(Utility, na.rm = T),
            mWFUt = mean(WFUt, na.rm = T),
            mWBUt= mean(WBUt, na.rm = T),
            mFishUt = mean(FishUt, na.rm = T),
            mAngUt = mean(AngUt, na.rm = T),
            mRampUt = mean(RampUt, na.rm = T))

dat2$month<-lubridate::month(dat2$Date)
dat2$day<-lubridate::day(dat2$Date)
dat2$month_day<-paste(dat2$month,dat2$day,sep="-")
dat2<-dat2 %>%
  dplyr::group_by(month,day) %>%
  dplyr::summarize(mUtility = mean(mUtility, na.rm = T),
            mWFUt = mean(mWFUt, na.rm = T),
            mWBUt= mean(mWBUt, na.rm = T),
            mFishUt = mean(mFishUt, na.rm = T),
            mAngUt = mean(mAngUt, na.rm = T),
            mRampUt = mean(mRampUt, na.rm = T))


ggplot(dat2, aes(day, mUtility, group = month, color = month)) +
  geom_line( )+
  labs(title="Monthly Utility of 11.3cms Paddlefish Discharge",
       y="Utility",
       x="Day of Month"
  )
# write.csv(dat2, "~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_11.3cms_discharge/9BoardsUtilities.csv")

```

```{r Monthly Plots, echo=FALSE}
One<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_0cms_discharge/9BoardsUtilities.csv")
One$Discharge<- rep("0 cms",nrow(One))
Two<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_2.825cms_discharge/9BoardsUtilities.csv")
Two$Discharge<- rep("2.825 cms",nrow(Two))
Three<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_5.65cms_discharge/9BoardsUtilities.csv")
Three$Discharge<- rep("5.65 cms",nrow(Three))
Four<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_8.475cms_discharge/9BoardsUtilities.csv")
Four$Discharge<- rep("8.475 cms",nrow(Four))
Five<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_11.3cms_discharge/9BoardsUtilities.csv")
Five$Discharge<- rep("11.3 cms",nrow(Five))
# Six<-read.csv("~/GitHub/Bluff-Lake-Project/_analysis/noxubee-discharge-states/paddlefish-discharges/weekly_16.95cms_discharge/9BoardsUtilities.csv")
# Six$Discharge<- rep(6,nrow(Six))

data<-rbind(One,Two,Three,Four,Five)
Jan<-subset(data, month==1)
ggplot(Jan, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="January- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month")+
  scale_colour_discrete(
            breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
            labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Feb<-subset(data, month==2)
ggplot(Feb, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="Feb- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Mar<-subset(data, month==3)
ggplot(Mar, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="March- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Apr<-subset(data, month==4)
ggplot(Apr, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="April- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
May<-subset(data, month==5)
ggplot(May, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="May- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Jun<-subset(data, month==6)
ggplot(Jun, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="June- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Jul<-subset(data, month==7)
ggplot(Jul, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="July- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Aug<-subset(data, month==8)
ggplot(Aug, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="August- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Sep<-subset(data, month==9)
ggplot(Sep, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="September- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Oct<-subset(data, month==10)
ggplot(Oct, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="October- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Nov<-subset(data, month==11)
ggplot(Nov, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="November- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
Dec<-subset(data, month==12)
ggplot(Dec, aes(day, mUtility, group = Discharge, color = Discharge)) +
  geom_line( )+
  labs(title="December- Utility of Paddlefish Discharges",
       y="Utility",
       x="Day of Month"
  )+
  scale_colour_discrete(
    breaks=c("0 cms", "2.825 cms", "5.65 cms", "8.475 cms", "11.3 cms"),
    labels=c("0", "2.825", "5.65", "8.475", "11.3"))
```

